config/routes.rb
Magazyn::Application.routes.draw do

  devise_for :users

  resources :users
  resources :orders
  resources :products

  match "logs" => "logs#show"

  namespace :api do
    resources :users, :except => [:new, :edit]
    resources :products, :except => [:new, :edit]
    resources :orders, only: [:index, :show, :update] do
      resources :products, only: [:index, :show, :update], controller: 'line_items'
    end
  end

  root :to => "users#index"

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :products, dependent: :destroy, class_name: "LineItem"
  accepts_nested_attributes_for :products, allow_destroy: true

  after_create :set_number

  scope :not_closed, where("state != ?", "closed")
  scope :ordered, order("id DESC")

  def set_number
    time = Time.zone.now
    update_attribute(:number, [id, time.month, time.year].join("/"))
  end

  def total_items
    products.count
  end


  state_machine :state, :initial => :new do
    event :activate do
      transition new: :open
    end

    event :process do
      transition open: :processed
    end

    event :close do
      transition processed: :closed
    end
  end

end

app/controllers/api/orders_controller.rb
class Api::OrdersController < Api::BaseController

  http_basic_authenticate_with name: Settings.auth.login, password: Settings.auth.passwd

  def index
    @orders = Order.not_closed
    respond_to do |format|
      format.xml
    end
  end

  def show
    @order = Order.not_closed.find(params[:id])
    respond_to do |format|
      format.xml
    end
  end

  def update
    @order = Order.not_closed.find(params[:id])

    if @order.update_attributes(params[:order])
      head :no_content
    else
      render xml: @order.errors, status: :unprocessable_entity
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.ordered
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(params[:order])

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path, notice: 'Order was successfully updated.'
  end
end

app/views/orders/_form.html.haml
= nested_form_for(@order) do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"

      %ul
      - @order.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :comment
    = f.text_area :comment

  %div.product_list
    %h3 List of products to order
    = f.fields_for :products do |line_item_form|
      = line_item_form.select(:product_id, Product.all.map { |p| [p.name, p.id] })
      = line_item_form.text_field :amount_needed, class: "input-mini"
      = line_item_form.link_to_remove "Remove this product"

    %p= f.link_to_add "Add a product", :products

  - unless @order.new_record?
    .field
      = f.label :state
      = f.select(:state, ["new", "processed", "closed"])

  .actions
    = f.submit class: "btn"

app/views/orders/edit.html.haml
%h1
  Editing order
  = @order.number

= render 'form'

= link_to 'Show', @order
|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th{style: "width: 20%"} Number
    %th{style: "width: 35%"} Comment
    %th State
    %th{style: "width: 5%"} Items
    %th{style: "width: 20%"} Options

  - @orders.each do |order|
    %tr
      %td= order.number
      %td= truncate order.comment, length: 60
      %td= order.state
      %td= order.total_items
      %td
        .btn-group
          = link_to 'Show', order, class: "btn"
          = link_to 'Edit', edit_order_path(order), class: "btn"
          = link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete, class: "btn"

%br

= link_to 'New order', new_order_path

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%h1= "Order #{@order.number}"

%p
  Comment:
  = @order.comment
%p
  State:
  %strong= @order.state
%div
  - if @order.products.present?
    Products:
    %table.table.table-striped.table-bordered.table-condensed
      %tr
        %th{style: "width: 25%"} Product
        %th{style: "width: 25%"} Current Stock
        %th{style: "width: 25%"} Need
        %th{style: "width: 25%"} Given

      - @order.products.each do |line_item|
        %tr
          %td= link_to line_item.product.name, line_item.product
          %td= line_item.product.stock
          %td= line_item.amount_needed
          %td= line_item.amount_given

  - else
    No products added yet

= link_to "Orders", orders_path