config/routes.rb
Magazyn::Application.routes.draw do

  devise_for :users

  resources :users
  resources :orders
  resources :products

  match "logs" => "logs#show"

  namespace :api do
    resources :users, :except => [:new, :edit]
    resources :products, :except => [:new, :edit]
    resources :orders, only: [:index, :show, :update] do
      resources :products, only: [:index, :show, :update], controller: 'line_items'
    end
  end

  root :to => "users#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :product_number, :photo_url, :price, :stock, :description, :removed

  validates :product_number, uniqueness: true,
                            numericality: {only_integer: true},
                            presence: true
  validates :photo_url, format: {with: URI::regexp(%w(http https))}
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :stock, presence: true, numericality: {only_integer: true}


end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::BaseController

  http_basic_authenticate_with name: Settings.auth.login, password: Settings.auth.passwd,
     except: [:index, :show]

  def index
    @products = Product.all
    render xml: @products, only: [:name, :description, :stock, :price, :photo_url, :removed, :product_number],
      skip_types: true, dasherize: false
  end

  def show
    @product = Product.find_by_product_number(params[:id])
    render xml: @product, only: [:name, :description, :stock, :price, :photo_url, :removed, :product_number],
      skip_types: true, dasherize: false
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      render xml: @product, status: :created, location: @product
    else
      render xml: @product.errors, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find_by_product_number(params[:id])

    if @product.update_attributes(params[:product])
      head :no_content
    else
      render xml: @product.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find_by_product_number(params[:id])
    @product.destroy

    head :no_content
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully updated.'
  end
end

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"

      %ul
      - @product.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :product_number
    = f.text_field :product_number
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :photo_url
    = f.text_field :photo_url
  .field
    = f.label :stock
    = f.text_field :stock
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :removed
    = f.check_box :removed
  .actions
    = f.submit class: "btn"

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', product_path(@product.product_number)
|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th{style: "width: 2%"} Number
    %th{style: "width: 12%"} Picture
    %th{style: "width: 10%"} Name
    %th{style: "width: 35%"} Description
    %th{style: "width: 5%"} Stock
    %th{style: "width: 5%"} Price
    %th{style: "width: 20%"} Options

  - @products.each do |product|
    %tr
      %td= product.product_number
      %td= product_photo(product)
      %td= product.name
      %td= truncate product.description, length: 60
      %td= product.stock
      %td= number_to_currency product.price
      %td
        .btn-group
          = link_to 'Show', product, class: "btn"
          = link_to 'Edit', edit_product_path(product), class: "btn"
          = link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete, class: "btn"

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1= @product.name

.row
  .span6
    %p
      = @product.description
  .span6
    = product_photo @product, "512x512"
.row
  .span12
    %p
      Stock:
      = @product.stock

    %p
      Price:
      = number_to_currency @product.price

    = link_to "Products", products_path